# -*- coding: utf-8 -*-
"""Tests Ex1 - Validator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yiPUz1iTmSQJmzmIsf6pvtETOaqz3mMK
"""



def validator():
  """
  This function asks the user for a list separated by spaces 
  and returns the product if said list.
  """

  while True:
    try:
      total = 1
      for x in split_list:
          total *= int(x) 
      return total
      break
    except:
      provided = input('Provide a list separated by spaces:')
      split_list = provided.split()

def main():
  total = validator()
  print(total)

if __name__ == "__main__":
  main()

